// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(CindermarkFFIFFI)
import CindermarkFFIFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_cindermark_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_cindermark_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol CindermarkParserProtocol : AnyObject {
    
    func extractWikiLinks(text: String)  -> [String]
    
    func parse(text: String)  -> FfiParseResult
    
    func parseEditable(text: String)  -> FfiParseResult
    
    func parseEditableIncremental(text: String, editUtf16Start: UInt32, editOldUtf16Len: UInt32, editNewUtf16Len: UInt32)  -> FfiIncrementalResult
    
    func parseEditableIncrementalStyleOnly(text: String, editUtf16Start: UInt32, editOldUtf16Len: UInt32, editNewUtf16Len: UInt32)  -> FfiIncrementalStyleResult
    
    func parseForSave(text: String, shortPreviewMax: UInt32, longPreviewMax: UInt32)  -> FfiSaveParseResult
    
    func renderPreview(text: String, maxChars: UInt32)  -> FfiRenderedPreview
    
    func renderPreviews(text: String, shortMax: UInt32, longMax: UInt32)  -> [FfiRenderedPreview]
    
    func resetState() 
    
    func toggleCheckbox(text: String, lineIndex: UInt32)  -> String
    
}

open class CindermarkParser:
    CindermarkParserProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_cindermark_fn_clone_cindermarkparser(self.pointer, $0) }
    }
public convenience init(imageMarkerScheme: String? = nil) {
    let pointer =
        try! rustCall() {
    uniffi_cindermark_fn_constructor_cindermarkparser_new(
        FfiConverterOptionString.lower(imageMarkerScheme),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_cindermark_fn_free_cindermarkparser(pointer, $0) }
    }

    

    
open func extractWikiLinks(text: String) -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_extract_wiki_links(self.uniffiClonePointer(),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func parse(text: String) -> FfiParseResult {
    return try!  FfiConverterTypeFfiParseResult.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_parse(self.uniffiClonePointer(),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func parseEditable(text: String) -> FfiParseResult {
    return try!  FfiConverterTypeFfiParseResult.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_parse_editable(self.uniffiClonePointer(),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func parseEditableIncremental(text: String, editUtf16Start: UInt32, editOldUtf16Len: UInt32, editNewUtf16Len: UInt32) -> FfiIncrementalResult {
    return try!  FfiConverterTypeFfiIncrementalResult.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_parse_editable_incremental(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(editUtf16Start),
        FfiConverterUInt32.lower(editOldUtf16Len),
        FfiConverterUInt32.lower(editNewUtf16Len),$0
    )
})
}
    
open func parseEditableIncrementalStyleOnly(text: String, editUtf16Start: UInt32, editOldUtf16Len: UInt32, editNewUtf16Len: UInt32) -> FfiIncrementalStyleResult {
    return try!  FfiConverterTypeFfiIncrementalStyleResult.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_parse_editable_incremental_style_only(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(editUtf16Start),
        FfiConverterUInt32.lower(editOldUtf16Len),
        FfiConverterUInt32.lower(editNewUtf16Len),$0
    )
})
}
    
open func parseForSave(text: String, shortPreviewMax: UInt32, longPreviewMax: UInt32) -> FfiSaveParseResult {
    return try!  FfiConverterTypeFfiSaveParseResult.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_parse_for_save(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(shortPreviewMax),
        FfiConverterUInt32.lower(longPreviewMax),$0
    )
})
}
    
open func renderPreview(text: String, maxChars: UInt32) -> FfiRenderedPreview {
    return try!  FfiConverterTypeFfiRenderedPreview.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_render_preview(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(maxChars),$0
    )
})
}
    
open func renderPreviews(text: String, shortMax: UInt32, longMax: UInt32) -> [FfiRenderedPreview] {
    return try!  FfiConverterSequenceTypeFfiRenderedPreview.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_render_previews(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(shortMax),
        FfiConverterUInt32.lower(longMax),$0
    )
})
}
    
open func resetState() {try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_reset_state(self.uniffiClonePointer(),$0
    )
}
}
    
open func toggleCheckbox(text: String, lineIndex: UInt32) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_cindermark_fn_method_cindermarkparser_toggle_checkbox(self.uniffiClonePointer(),
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(lineIndex),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCindermarkParser: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = CindermarkParser

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> CindermarkParser {
        return CindermarkParser(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: CindermarkParser) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CindermarkParser {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: CindermarkParser, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCindermarkParser_lift(_ pointer: UnsafeMutableRawPointer) throws -> CindermarkParser {
    return try FfiConverterTypeCindermarkParser.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCindermarkParser_lower(_ value: CindermarkParser) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCindermarkParser.lower(value)
}


public struct FfiBlock {
    public let blockType: FfiBlockType
    public let lineStart: UInt32
    public let lineEnd: UInt32
    public let utf16Start: UInt32
    public let utf16End: UInt32
    public let listIndent: UInt32
    public let markerUtf16Start: UInt32
    public let markerUtf16End: UInt32
    public let markerSource: String
    public let unorderedMarker: String
    public let orderedDelimiter: String
    public let orderedRawNumber: String
    public let headingLevel: UInt8
    public let number: UInt32
    public let isChecked: Bool
    public let language: String?
    public let text: String
    public let inlineSpans: [FfiInlineSpan]
    public let listItems: [FfiListItem]
    public let tableHeaders: [String]
    public let tableRows: [[String]]
    public let tableAlignments: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blockType: FfiBlockType, lineStart: UInt32, lineEnd: UInt32, utf16Start: UInt32, utf16End: UInt32, listIndent: UInt32, markerUtf16Start: UInt32, markerUtf16End: UInt32, markerSource: String, unorderedMarker: String, orderedDelimiter: String, orderedRawNumber: String, headingLevel: UInt8, number: UInt32, isChecked: Bool, language: String?, text: String, inlineSpans: [FfiInlineSpan], listItems: [FfiListItem], tableHeaders: [String], tableRows: [[String]], tableAlignments: [UInt8]) {
        self.blockType = blockType
        self.lineStart = lineStart
        self.lineEnd = lineEnd
        self.utf16Start = utf16Start
        self.utf16End = utf16End
        self.listIndent = listIndent
        self.markerUtf16Start = markerUtf16Start
        self.markerUtf16End = markerUtf16End
        self.markerSource = markerSource
        self.unorderedMarker = unorderedMarker
        self.orderedDelimiter = orderedDelimiter
        self.orderedRawNumber = orderedRawNumber
        self.headingLevel = headingLevel
        self.number = number
        self.isChecked = isChecked
        self.language = language
        self.text = text
        self.inlineSpans = inlineSpans
        self.listItems = listItems
        self.tableHeaders = tableHeaders
        self.tableRows = tableRows
        self.tableAlignments = tableAlignments
    }
}



extension FfiBlock: Equatable, Hashable {
    public static func ==(lhs: FfiBlock, rhs: FfiBlock) -> Bool {
        if lhs.blockType != rhs.blockType {
            return false
        }
        if lhs.lineStart != rhs.lineStart {
            return false
        }
        if lhs.lineEnd != rhs.lineEnd {
            return false
        }
        if lhs.utf16Start != rhs.utf16Start {
            return false
        }
        if lhs.utf16End != rhs.utf16End {
            return false
        }
        if lhs.listIndent != rhs.listIndent {
            return false
        }
        if lhs.markerUtf16Start != rhs.markerUtf16Start {
            return false
        }
        if lhs.markerUtf16End != rhs.markerUtf16End {
            return false
        }
        if lhs.markerSource != rhs.markerSource {
            return false
        }
        if lhs.unorderedMarker != rhs.unorderedMarker {
            return false
        }
        if lhs.orderedDelimiter != rhs.orderedDelimiter {
            return false
        }
        if lhs.orderedRawNumber != rhs.orderedRawNumber {
            return false
        }
        if lhs.headingLevel != rhs.headingLevel {
            return false
        }
        if lhs.number != rhs.number {
            return false
        }
        if lhs.isChecked != rhs.isChecked {
            return false
        }
        if lhs.language != rhs.language {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        if lhs.inlineSpans != rhs.inlineSpans {
            return false
        }
        if lhs.listItems != rhs.listItems {
            return false
        }
        if lhs.tableHeaders != rhs.tableHeaders {
            return false
        }
        if lhs.tableRows != rhs.tableRows {
            return false
        }
        if lhs.tableAlignments != rhs.tableAlignments {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blockType)
        hasher.combine(lineStart)
        hasher.combine(lineEnd)
        hasher.combine(utf16Start)
        hasher.combine(utf16End)
        hasher.combine(listIndent)
        hasher.combine(markerUtf16Start)
        hasher.combine(markerUtf16End)
        hasher.combine(markerSource)
        hasher.combine(unorderedMarker)
        hasher.combine(orderedDelimiter)
        hasher.combine(orderedRawNumber)
        hasher.combine(headingLevel)
        hasher.combine(number)
        hasher.combine(isChecked)
        hasher.combine(language)
        hasher.combine(text)
        hasher.combine(inlineSpans)
        hasher.combine(listItems)
        hasher.combine(tableHeaders)
        hasher.combine(tableRows)
        hasher.combine(tableAlignments)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiBlock: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiBlock {
        return
            try FfiBlock(
                blockType: FfiConverterTypeFfiBlockType.read(from: &buf), 
                lineStart: FfiConverterUInt32.read(from: &buf), 
                lineEnd: FfiConverterUInt32.read(from: &buf), 
                utf16Start: FfiConverterUInt32.read(from: &buf), 
                utf16End: FfiConverterUInt32.read(from: &buf), 
                listIndent: FfiConverterUInt32.read(from: &buf), 
                markerUtf16Start: FfiConverterUInt32.read(from: &buf), 
                markerUtf16End: FfiConverterUInt32.read(from: &buf), 
                markerSource: FfiConverterString.read(from: &buf), 
                unorderedMarker: FfiConverterString.read(from: &buf), 
                orderedDelimiter: FfiConverterString.read(from: &buf), 
                orderedRawNumber: FfiConverterString.read(from: &buf), 
                headingLevel: FfiConverterUInt8.read(from: &buf), 
                number: FfiConverterUInt32.read(from: &buf), 
                isChecked: FfiConverterBool.read(from: &buf), 
                language: FfiConverterOptionString.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                inlineSpans: FfiConverterSequenceTypeFfiInlineSpan.read(from: &buf), 
                listItems: FfiConverterSequenceTypeFfiListItem.read(from: &buf), 
                tableHeaders: FfiConverterSequenceString.read(from: &buf), 
                tableRows: FfiConverterSequenceSequenceString.read(from: &buf), 
                tableAlignments: FfiConverterSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: FfiBlock, into buf: inout [UInt8]) {
        FfiConverterTypeFfiBlockType.write(value.blockType, into: &buf)
        FfiConverterUInt32.write(value.lineStart, into: &buf)
        FfiConverterUInt32.write(value.lineEnd, into: &buf)
        FfiConverterUInt32.write(value.utf16Start, into: &buf)
        FfiConverterUInt32.write(value.utf16End, into: &buf)
        FfiConverterUInt32.write(value.listIndent, into: &buf)
        FfiConverterUInt32.write(value.markerUtf16Start, into: &buf)
        FfiConverterUInt32.write(value.markerUtf16End, into: &buf)
        FfiConverterString.write(value.markerSource, into: &buf)
        FfiConverterString.write(value.unorderedMarker, into: &buf)
        FfiConverterString.write(value.orderedDelimiter, into: &buf)
        FfiConverterString.write(value.orderedRawNumber, into: &buf)
        FfiConverterUInt8.write(value.headingLevel, into: &buf)
        FfiConverterUInt32.write(value.number, into: &buf)
        FfiConverterBool.write(value.isChecked, into: &buf)
        FfiConverterOptionString.write(value.language, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterSequenceTypeFfiInlineSpan.write(value.inlineSpans, into: &buf)
        FfiConverterSequenceTypeFfiListItem.write(value.listItems, into: &buf)
        FfiConverterSequenceString.write(value.tableHeaders, into: &buf)
        FfiConverterSequenceSequenceString.write(value.tableRows, into: &buf)
        FfiConverterSequenceUInt8.write(value.tableAlignments, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBlock_lift(_ buf: RustBuffer) throws -> FfiBlock {
    return try FfiConverterTypeFfiBlock.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBlock_lower(_ value: FfiBlock) -> RustBuffer {
    return FfiConverterTypeFfiBlock.lower(value)
}


public struct FfiDocumentStats {
    public let wordCount: UInt32
    public let characterCount: UInt32
    public let characterCountNoSpaces: UInt32
    public let paragraphCount: UInt32
    public let sentenceCount: UInt32
    public let checkboxTotal: UInt32
    public let checkboxCompleted: UInt32
    public let readingTimeSeconds: UInt32
    public let headingCount: UInt32
    public let linkCount: UInt32
    public let codeBlockCount: UInt32
    public let mermaidDiagramCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(wordCount: UInt32, characterCount: UInt32, characterCountNoSpaces: UInt32, paragraphCount: UInt32, sentenceCount: UInt32, checkboxTotal: UInt32, checkboxCompleted: UInt32, readingTimeSeconds: UInt32, headingCount: UInt32, linkCount: UInt32, codeBlockCount: UInt32, mermaidDiagramCount: UInt32) {
        self.wordCount = wordCount
        self.characterCount = characterCount
        self.characterCountNoSpaces = characterCountNoSpaces
        self.paragraphCount = paragraphCount
        self.sentenceCount = sentenceCount
        self.checkboxTotal = checkboxTotal
        self.checkboxCompleted = checkboxCompleted
        self.readingTimeSeconds = readingTimeSeconds
        self.headingCount = headingCount
        self.linkCount = linkCount
        self.codeBlockCount = codeBlockCount
        self.mermaidDiagramCount = mermaidDiagramCount
    }
}



extension FfiDocumentStats: Equatable, Hashable {
    public static func ==(lhs: FfiDocumentStats, rhs: FfiDocumentStats) -> Bool {
        if lhs.wordCount != rhs.wordCount {
            return false
        }
        if lhs.characterCount != rhs.characterCount {
            return false
        }
        if lhs.characterCountNoSpaces != rhs.characterCountNoSpaces {
            return false
        }
        if lhs.paragraphCount != rhs.paragraphCount {
            return false
        }
        if lhs.sentenceCount != rhs.sentenceCount {
            return false
        }
        if lhs.checkboxTotal != rhs.checkboxTotal {
            return false
        }
        if lhs.checkboxCompleted != rhs.checkboxCompleted {
            return false
        }
        if lhs.readingTimeSeconds != rhs.readingTimeSeconds {
            return false
        }
        if lhs.headingCount != rhs.headingCount {
            return false
        }
        if lhs.linkCount != rhs.linkCount {
            return false
        }
        if lhs.codeBlockCount != rhs.codeBlockCount {
            return false
        }
        if lhs.mermaidDiagramCount != rhs.mermaidDiagramCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(wordCount)
        hasher.combine(characterCount)
        hasher.combine(characterCountNoSpaces)
        hasher.combine(paragraphCount)
        hasher.combine(sentenceCount)
        hasher.combine(checkboxTotal)
        hasher.combine(checkboxCompleted)
        hasher.combine(readingTimeSeconds)
        hasher.combine(headingCount)
        hasher.combine(linkCount)
        hasher.combine(codeBlockCount)
        hasher.combine(mermaidDiagramCount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDocumentStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDocumentStats {
        return
            try FfiDocumentStats(
                wordCount: FfiConverterUInt32.read(from: &buf), 
                characterCount: FfiConverterUInt32.read(from: &buf), 
                characterCountNoSpaces: FfiConverterUInt32.read(from: &buf), 
                paragraphCount: FfiConverterUInt32.read(from: &buf), 
                sentenceCount: FfiConverterUInt32.read(from: &buf), 
                checkboxTotal: FfiConverterUInt32.read(from: &buf), 
                checkboxCompleted: FfiConverterUInt32.read(from: &buf), 
                readingTimeSeconds: FfiConverterUInt32.read(from: &buf), 
                headingCount: FfiConverterUInt32.read(from: &buf), 
                linkCount: FfiConverterUInt32.read(from: &buf), 
                codeBlockCount: FfiConverterUInt32.read(from: &buf), 
                mermaidDiagramCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDocumentStats, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.wordCount, into: &buf)
        FfiConverterUInt32.write(value.characterCount, into: &buf)
        FfiConverterUInt32.write(value.characterCountNoSpaces, into: &buf)
        FfiConverterUInt32.write(value.paragraphCount, into: &buf)
        FfiConverterUInt32.write(value.sentenceCount, into: &buf)
        FfiConverterUInt32.write(value.checkboxTotal, into: &buf)
        FfiConverterUInt32.write(value.checkboxCompleted, into: &buf)
        FfiConverterUInt32.write(value.readingTimeSeconds, into: &buf)
        FfiConverterUInt32.write(value.headingCount, into: &buf)
        FfiConverterUInt32.write(value.linkCount, into: &buf)
        FfiConverterUInt32.write(value.codeBlockCount, into: &buf)
        FfiConverterUInt32.write(value.mermaidDiagramCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDocumentStats_lift(_ buf: RustBuffer) throws -> FfiDocumentStats {
    return try FfiConverterTypeFfiDocumentStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDocumentStats_lower(_ value: FfiDocumentStats) -> RustBuffer {
    return FfiConverterTypeFfiDocumentStats.lower(value)
}


public struct FfiHeading {
    public let level: UInt8
    public let text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(level: UInt8, text: String) {
        self.level = level
        self.text = text
    }
}



extension FfiHeading: Equatable, Hashable {
    public static func ==(lhs: FfiHeading, rhs: FfiHeading) -> Bool {
        if lhs.level != rhs.level {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(level)
        hasher.combine(text)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHeading: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHeading {
        return
            try FfiHeading(
                level: FfiConverterUInt8.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiHeading, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.level, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHeading_lift(_ buf: RustBuffer) throws -> FfiHeading {
    return try FfiConverterTypeFfiHeading.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHeading_lower(_ value: FfiHeading) -> RustBuffer {
    return FfiConverterTypeFfiHeading.lower(value)
}


public struct FfiIncrementalResult {
    public let blocks: [FfiBlock]
    public let lineCount: UInt32
    public let dirtyStart: UInt32
    public let dirtyEnd: UInt32
    public let stats: FfiDocumentStats

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blocks: [FfiBlock], lineCount: UInt32, dirtyStart: UInt32, dirtyEnd: UInt32, stats: FfiDocumentStats) {
        self.blocks = blocks
        self.lineCount = lineCount
        self.dirtyStart = dirtyStart
        self.dirtyEnd = dirtyEnd
        self.stats = stats
    }
}



extension FfiIncrementalResult: Equatable, Hashable {
    public static func ==(lhs: FfiIncrementalResult, rhs: FfiIncrementalResult) -> Bool {
        if lhs.blocks != rhs.blocks {
            return false
        }
        if lhs.lineCount != rhs.lineCount {
            return false
        }
        if lhs.dirtyStart != rhs.dirtyStart {
            return false
        }
        if lhs.dirtyEnd != rhs.dirtyEnd {
            return false
        }
        if lhs.stats != rhs.stats {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blocks)
        hasher.combine(lineCount)
        hasher.combine(dirtyStart)
        hasher.combine(dirtyEnd)
        hasher.combine(stats)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiIncrementalResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiIncrementalResult {
        return
            try FfiIncrementalResult(
                blocks: FfiConverterSequenceTypeFfiBlock.read(from: &buf), 
                lineCount: FfiConverterUInt32.read(from: &buf), 
                dirtyStart: FfiConverterUInt32.read(from: &buf), 
                dirtyEnd: FfiConverterUInt32.read(from: &buf), 
                stats: FfiConverterTypeFfiDocumentStats.read(from: &buf)
        )
    }

    public static func write(_ value: FfiIncrementalResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiBlock.write(value.blocks, into: &buf)
        FfiConverterUInt32.write(value.lineCount, into: &buf)
        FfiConverterUInt32.write(value.dirtyStart, into: &buf)
        FfiConverterUInt32.write(value.dirtyEnd, into: &buf)
        FfiConverterTypeFfiDocumentStats.write(value.stats, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIncrementalResult_lift(_ buf: RustBuffer) throws -> FfiIncrementalResult {
    return try FfiConverterTypeFfiIncrementalResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIncrementalResult_lower(_ value: FfiIncrementalResult) -> RustBuffer {
    return FfiConverterTypeFfiIncrementalResult.lower(value)
}


public struct FfiIncrementalStyleResult {
    public let blocks: [FfiBlock]
    public let lineCount: UInt32
    public let dirtyStart: UInt32
    public let dirtyEnd: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blocks: [FfiBlock], lineCount: UInt32, dirtyStart: UInt32, dirtyEnd: UInt32) {
        self.blocks = blocks
        self.lineCount = lineCount
        self.dirtyStart = dirtyStart
        self.dirtyEnd = dirtyEnd
    }
}



extension FfiIncrementalStyleResult: Equatable, Hashable {
    public static func ==(lhs: FfiIncrementalStyleResult, rhs: FfiIncrementalStyleResult) -> Bool {
        if lhs.blocks != rhs.blocks {
            return false
        }
        if lhs.lineCount != rhs.lineCount {
            return false
        }
        if lhs.dirtyStart != rhs.dirtyStart {
            return false
        }
        if lhs.dirtyEnd != rhs.dirtyEnd {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blocks)
        hasher.combine(lineCount)
        hasher.combine(dirtyStart)
        hasher.combine(dirtyEnd)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiIncrementalStyleResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiIncrementalStyleResult {
        return
            try FfiIncrementalStyleResult(
                blocks: FfiConverterSequenceTypeFfiBlock.read(from: &buf), 
                lineCount: FfiConverterUInt32.read(from: &buf), 
                dirtyStart: FfiConverterUInt32.read(from: &buf), 
                dirtyEnd: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiIncrementalStyleResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiBlock.write(value.blocks, into: &buf)
        FfiConverterUInt32.write(value.lineCount, into: &buf)
        FfiConverterUInt32.write(value.dirtyStart, into: &buf)
        FfiConverterUInt32.write(value.dirtyEnd, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIncrementalStyleResult_lift(_ buf: RustBuffer) throws -> FfiIncrementalStyleResult {
    return try FfiConverterTypeFfiIncrementalStyleResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIncrementalStyleResult_lower(_ value: FfiIncrementalStyleResult) -> RustBuffer {
    return FfiConverterTypeFfiIncrementalStyleResult.lower(value)
}


public struct FfiInlineSpan {
    public let inlineType: FfiInlineType
    public let utf16Start: UInt32
    public let utf16End: UInt32
    public let contentUtf16Start: UInt32
    public let contentUtf16End: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(inlineType: FfiInlineType, utf16Start: UInt32, utf16End: UInt32, contentUtf16Start: UInt32, contentUtf16End: UInt32) {
        self.inlineType = inlineType
        self.utf16Start = utf16Start
        self.utf16End = utf16End
        self.contentUtf16Start = contentUtf16Start
        self.contentUtf16End = contentUtf16End
    }
}



extension FfiInlineSpan: Equatable, Hashable {
    public static func ==(lhs: FfiInlineSpan, rhs: FfiInlineSpan) -> Bool {
        if lhs.inlineType != rhs.inlineType {
            return false
        }
        if lhs.utf16Start != rhs.utf16Start {
            return false
        }
        if lhs.utf16End != rhs.utf16End {
            return false
        }
        if lhs.contentUtf16Start != rhs.contentUtf16Start {
            return false
        }
        if lhs.contentUtf16End != rhs.contentUtf16End {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(inlineType)
        hasher.combine(utf16Start)
        hasher.combine(utf16End)
        hasher.combine(contentUtf16Start)
        hasher.combine(contentUtf16End)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiInlineSpan: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiInlineSpan {
        return
            try FfiInlineSpan(
                inlineType: FfiConverterTypeFfiInlineType.read(from: &buf), 
                utf16Start: FfiConverterUInt32.read(from: &buf), 
                utf16End: FfiConverterUInt32.read(from: &buf), 
                contentUtf16Start: FfiConverterUInt32.read(from: &buf), 
                contentUtf16End: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiInlineSpan, into buf: inout [UInt8]) {
        FfiConverterTypeFfiInlineType.write(value.inlineType, into: &buf)
        FfiConverterUInt32.write(value.utf16Start, into: &buf)
        FfiConverterUInt32.write(value.utf16End, into: &buf)
        FfiConverterUInt32.write(value.contentUtf16Start, into: &buf)
        FfiConverterUInt32.write(value.contentUtf16End, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiInlineSpan_lift(_ buf: RustBuffer) throws -> FfiInlineSpan {
    return try FfiConverterTypeFfiInlineSpan.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiInlineSpan_lower(_ value: FfiInlineSpan) -> RustBuffer {
    return FfiConverterTypeFfiInlineSpan.lower(value)
}


public struct FfiListItem {
    public let text: String
    public let inlineSpans: [FfiInlineSpan]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, inlineSpans: [FfiInlineSpan]) {
        self.text = text
        self.inlineSpans = inlineSpans
    }
}



extension FfiListItem: Equatable, Hashable {
    public static func ==(lhs: FfiListItem, rhs: FfiListItem) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.inlineSpans != rhs.inlineSpans {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(inlineSpans)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiListItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiListItem {
        return
            try FfiListItem(
                text: FfiConverterString.read(from: &buf), 
                inlineSpans: FfiConverterSequenceTypeFfiInlineSpan.read(from: &buf)
        )
    }

    public static func write(_ value: FfiListItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterSequenceTypeFfiInlineSpan.write(value.inlineSpans, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiListItem_lift(_ buf: RustBuffer) throws -> FfiListItem {
    return try FfiConverterTypeFfiListItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiListItem_lower(_ value: FfiListItem) -> RustBuffer {
    return FfiConverterTypeFfiListItem.lower(value)
}


public struct FfiParseResult {
    public let blocks: [FfiBlock]
    public let lineCount: UInt32
    public let stats: FfiDocumentStats
    public let wikiLinks: [String]
    public let headings: [FfiHeading]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blocks: [FfiBlock], lineCount: UInt32, stats: FfiDocumentStats, wikiLinks: [String], headings: [FfiHeading]) {
        self.blocks = blocks
        self.lineCount = lineCount
        self.stats = stats
        self.wikiLinks = wikiLinks
        self.headings = headings
    }
}



extension FfiParseResult: Equatable, Hashable {
    public static func ==(lhs: FfiParseResult, rhs: FfiParseResult) -> Bool {
        if lhs.blocks != rhs.blocks {
            return false
        }
        if lhs.lineCount != rhs.lineCount {
            return false
        }
        if lhs.stats != rhs.stats {
            return false
        }
        if lhs.wikiLinks != rhs.wikiLinks {
            return false
        }
        if lhs.headings != rhs.headings {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blocks)
        hasher.combine(lineCount)
        hasher.combine(stats)
        hasher.combine(wikiLinks)
        hasher.combine(headings)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiParseResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiParseResult {
        return
            try FfiParseResult(
                blocks: FfiConverterSequenceTypeFfiBlock.read(from: &buf), 
                lineCount: FfiConverterUInt32.read(from: &buf), 
                stats: FfiConverterTypeFfiDocumentStats.read(from: &buf), 
                wikiLinks: FfiConverterSequenceString.read(from: &buf), 
                headings: FfiConverterSequenceTypeFfiHeading.read(from: &buf)
        )
    }

    public static func write(_ value: FfiParseResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiBlock.write(value.blocks, into: &buf)
        FfiConverterUInt32.write(value.lineCount, into: &buf)
        FfiConverterTypeFfiDocumentStats.write(value.stats, into: &buf)
        FfiConverterSequenceString.write(value.wikiLinks, into: &buf)
        FfiConverterSequenceTypeFfiHeading.write(value.headings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiParseResult_lift(_ buf: RustBuffer) throws -> FfiParseResult {
    return try FfiConverterTypeFfiParseResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiParseResult_lower(_ value: FfiParseResult) -> RustBuffer {
    return FfiConverterTypeFfiParseResult.lower(value)
}


public struct FfiPreviewSpan {
    public let spanType: FfiInlineType
    public let start: UInt32
    public let end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(spanType: FfiInlineType, start: UInt32, end: UInt32) {
        self.spanType = spanType
        self.start = start
        self.end = end
    }
}



extension FfiPreviewSpan: Equatable, Hashable {
    public static func ==(lhs: FfiPreviewSpan, rhs: FfiPreviewSpan) -> Bool {
        if lhs.spanType != rhs.spanType {
            return false
        }
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(spanType)
        hasher.combine(start)
        hasher.combine(end)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPreviewSpan: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPreviewSpan {
        return
            try FfiPreviewSpan(
                spanType: FfiConverterTypeFfiInlineType.read(from: &buf), 
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPreviewSpan, into buf: inout [UInt8]) {
        FfiConverterTypeFfiInlineType.write(value.spanType, into: &buf)
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPreviewSpan_lift(_ buf: RustBuffer) throws -> FfiPreviewSpan {
    return try FfiConverterTypeFfiPreviewSpan.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPreviewSpan_lower(_ value: FfiPreviewSpan) -> RustBuffer {
    return FfiConverterTypeFfiPreviewSpan.lower(value)
}


public struct FfiRenderedPreview {
    public let plainText: String
    public let spans: [FfiPreviewSpan]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(plainText: String, spans: [FfiPreviewSpan]) {
        self.plainText = plainText
        self.spans = spans
    }
}



extension FfiRenderedPreview: Equatable, Hashable {
    public static func ==(lhs: FfiRenderedPreview, rhs: FfiRenderedPreview) -> Bool {
        if lhs.plainText != rhs.plainText {
            return false
        }
        if lhs.spans != rhs.spans {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(plainText)
        hasher.combine(spans)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRenderedPreview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRenderedPreview {
        return
            try FfiRenderedPreview(
                plainText: FfiConverterString.read(from: &buf), 
                spans: FfiConverterSequenceTypeFfiPreviewSpan.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRenderedPreview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.plainText, into: &buf)
        FfiConverterSequenceTypeFfiPreviewSpan.write(value.spans, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRenderedPreview_lift(_ buf: RustBuffer) throws -> FfiRenderedPreview {
    return try FfiConverterTypeFfiRenderedPreview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRenderedPreview_lower(_ value: FfiRenderedPreview) -> RustBuffer {
    return FfiConverterTypeFfiRenderedPreview.lower(value)
}


public struct FfiSaveParseResult {
    public let blocks: [FfiBlock]
    public let lineCount: UInt32
    public let stats: FfiDocumentStats
    public let wikiLinks: [String]
    public let headings: [FfiHeading]
    public let shortPreview: FfiRenderedPreview
    public let longPreview: FfiRenderedPreview

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blocks: [FfiBlock], lineCount: UInt32, stats: FfiDocumentStats, wikiLinks: [String], headings: [FfiHeading], shortPreview: FfiRenderedPreview, longPreview: FfiRenderedPreview) {
        self.blocks = blocks
        self.lineCount = lineCount
        self.stats = stats
        self.wikiLinks = wikiLinks
        self.headings = headings
        self.shortPreview = shortPreview
        self.longPreview = longPreview
    }
}



extension FfiSaveParseResult: Equatable, Hashable {
    public static func ==(lhs: FfiSaveParseResult, rhs: FfiSaveParseResult) -> Bool {
        if lhs.blocks != rhs.blocks {
            return false
        }
        if lhs.lineCount != rhs.lineCount {
            return false
        }
        if lhs.stats != rhs.stats {
            return false
        }
        if lhs.wikiLinks != rhs.wikiLinks {
            return false
        }
        if lhs.headings != rhs.headings {
            return false
        }
        if lhs.shortPreview != rhs.shortPreview {
            return false
        }
        if lhs.longPreview != rhs.longPreview {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blocks)
        hasher.combine(lineCount)
        hasher.combine(stats)
        hasher.combine(wikiLinks)
        hasher.combine(headings)
        hasher.combine(shortPreview)
        hasher.combine(longPreview)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSaveParseResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSaveParseResult {
        return
            try FfiSaveParseResult(
                blocks: FfiConverterSequenceTypeFfiBlock.read(from: &buf), 
                lineCount: FfiConverterUInt32.read(from: &buf), 
                stats: FfiConverterTypeFfiDocumentStats.read(from: &buf), 
                wikiLinks: FfiConverterSequenceString.read(from: &buf), 
                headings: FfiConverterSequenceTypeFfiHeading.read(from: &buf), 
                shortPreview: FfiConverterTypeFfiRenderedPreview.read(from: &buf), 
                longPreview: FfiConverterTypeFfiRenderedPreview.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSaveParseResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiBlock.write(value.blocks, into: &buf)
        FfiConverterUInt32.write(value.lineCount, into: &buf)
        FfiConverterTypeFfiDocumentStats.write(value.stats, into: &buf)
        FfiConverterSequenceString.write(value.wikiLinks, into: &buf)
        FfiConverterSequenceTypeFfiHeading.write(value.headings, into: &buf)
        FfiConverterTypeFfiRenderedPreview.write(value.shortPreview, into: &buf)
        FfiConverterTypeFfiRenderedPreview.write(value.longPreview, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSaveParseResult_lift(_ buf: RustBuffer) throws -> FfiSaveParseResult {
    return try FfiConverterTypeFfiSaveParseResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSaveParseResult_lower(_ value: FfiSaveParseResult) -> RustBuffer {
    return FfiConverterTypeFfiSaveParseResult.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiBlockType {
    
    case heading
    case paragraph
    case codeBlock
    case blockquote
    case bulletList
    case orderedList
    case checkbox
    case table
    case horizontalRule
    case empty
    case footnoteDefinition
    case imageMarker
    case bulletItem
    case numberedItem
    case callout(kind: UInt8
    )
    case mermaidDiagram(diagramType: UInt8
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiBlockType: FfiConverterRustBuffer {
    typealias SwiftType = FfiBlockType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiBlockType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .heading
        
        case 2: return .paragraph
        
        case 3: return .codeBlock
        
        case 4: return .blockquote
        
        case 5: return .bulletList
        
        case 6: return .orderedList
        
        case 7: return .checkbox
        
        case 8: return .table
        
        case 9: return .horizontalRule
        
        case 10: return .empty
        
        case 11: return .footnoteDefinition
        
        case 12: return .imageMarker
        
        case 13: return .bulletItem
        
        case 14: return .numberedItem
        
        case 15: return .callout(kind: try FfiConverterUInt8.read(from: &buf)
        )
        
        case 16: return .mermaidDiagram(diagramType: try FfiConverterUInt8.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiBlockType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .heading:
            writeInt(&buf, Int32(1))
        
        
        case .paragraph:
            writeInt(&buf, Int32(2))
        
        
        case .codeBlock:
            writeInt(&buf, Int32(3))
        
        
        case .blockquote:
            writeInt(&buf, Int32(4))
        
        
        case .bulletList:
            writeInt(&buf, Int32(5))
        
        
        case .orderedList:
            writeInt(&buf, Int32(6))
        
        
        case .checkbox:
            writeInt(&buf, Int32(7))
        
        
        case .table:
            writeInt(&buf, Int32(8))
        
        
        case .horizontalRule:
            writeInt(&buf, Int32(9))
        
        
        case .empty:
            writeInt(&buf, Int32(10))
        
        
        case .footnoteDefinition:
            writeInt(&buf, Int32(11))
        
        
        case .imageMarker:
            writeInt(&buf, Int32(12))
        
        
        case .bulletItem:
            writeInt(&buf, Int32(13))
        
        
        case .numberedItem:
            writeInt(&buf, Int32(14))
        
        
        case let .callout(kind):
            writeInt(&buf, Int32(15))
            FfiConverterUInt8.write(kind, into: &buf)
            
        
        case let .mermaidDiagram(diagramType):
            writeInt(&buf, Int32(16))
            FfiConverterUInt8.write(diagramType, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBlockType_lift(_ buf: RustBuffer) throws -> FfiBlockType {
    return try FfiConverterTypeFfiBlockType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBlockType_lower(_ value: FfiBlockType) -> RustBuffer {
    return FfiConverterTypeFfiBlockType.lower(value)
}



extension FfiBlockType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiInlineType {
    
    case bold
    case italic
    case boldItalic
    case strikethrough
    case underlineTilde
    case underlineHtml
    case inlineCode
    case highlight
    case highlightColor(colorIndex: UInt8
    )
    case highlightHex(hex: String
    )
    case link(url: String
    )
    case autoLink(url: String
    )
    case wikiLink
    case footnoteRef
    case comment
    case hexColor(hex: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiInlineType: FfiConverterRustBuffer {
    typealias SwiftType = FfiInlineType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiInlineType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bold
        
        case 2: return .italic
        
        case 3: return .boldItalic
        
        case 4: return .strikethrough
        
        case 5: return .underlineTilde
        
        case 6: return .underlineHtml
        
        case 7: return .inlineCode
        
        case 8: return .highlight
        
        case 9: return .highlightColor(colorIndex: try FfiConverterUInt8.read(from: &buf)
        )
        
        case 10: return .highlightHex(hex: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .link(url: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .autoLink(url: try FfiConverterString.read(from: &buf)
        )
        
        case 13: return .wikiLink
        
        case 14: return .footnoteRef
        
        case 15: return .comment
        
        case 16: return .hexColor(hex: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiInlineType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bold:
            writeInt(&buf, Int32(1))
        
        
        case .italic:
            writeInt(&buf, Int32(2))
        
        
        case .boldItalic:
            writeInt(&buf, Int32(3))
        
        
        case .strikethrough:
            writeInt(&buf, Int32(4))
        
        
        case .underlineTilde:
            writeInt(&buf, Int32(5))
        
        
        case .underlineHtml:
            writeInt(&buf, Int32(6))
        
        
        case .inlineCode:
            writeInt(&buf, Int32(7))
        
        
        case .highlight:
            writeInt(&buf, Int32(8))
        
        
        case let .highlightColor(colorIndex):
            writeInt(&buf, Int32(9))
            FfiConverterUInt8.write(colorIndex, into: &buf)
            
        
        case let .highlightHex(hex):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(hex, into: &buf)
            
        
        case let .link(url):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(url, into: &buf)
            
        
        case let .autoLink(url):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(url, into: &buf)
            
        
        case .wikiLink:
            writeInt(&buf, Int32(13))
        
        
        case .footnoteRef:
            writeInt(&buf, Int32(14))
        
        
        case .comment:
            writeInt(&buf, Int32(15))
        
        
        case let .hexColor(hex):
            writeInt(&buf, Int32(16))
            FfiConverterString.write(hex, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiInlineType_lift(_ buf: RustBuffer) throws -> FfiInlineType {
    return try FfiConverterTypeFfiInlineType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiInlineType_lower(_ value: FfiInlineType) -> RustBuffer {
    return FfiConverterTypeFfiInlineType.lower(value)
}



extension FfiInlineType: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiBlock: FfiConverterRustBuffer {
    typealias SwiftType = [FfiBlock]

    public static func write(_ value: [FfiBlock], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiBlock.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiBlock] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiBlock]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiBlock.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiHeading: FfiConverterRustBuffer {
    typealias SwiftType = [FfiHeading]

    public static func write(_ value: [FfiHeading], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiHeading.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiHeading] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiHeading]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiHeading.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiInlineSpan: FfiConverterRustBuffer {
    typealias SwiftType = [FfiInlineSpan]

    public static func write(_ value: [FfiInlineSpan], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiInlineSpan.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiInlineSpan] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiInlineSpan]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiInlineSpan.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiListItem: FfiConverterRustBuffer {
    typealias SwiftType = [FfiListItem]

    public static func write(_ value: [FfiListItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiListItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiListItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiListItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiListItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiPreviewSpan: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPreviewSpan]

    public static func write(_ value: [FfiPreviewSpan], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPreviewSpan.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPreviewSpan] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPreviewSpan]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiPreviewSpan.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiRenderedPreview: FfiConverterRustBuffer {
    typealias SwiftType = [FfiRenderedPreview]

    public static func write(_ value: [FfiRenderedPreview], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiRenderedPreview.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiRenderedPreview] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiRenderedPreview]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiRenderedPreview.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [[String]]

    public static func write(_ value: [[String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[String]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[String]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceString.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_cindermark_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_extract_wiki_links() != 56235) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_parse() != 5574) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_parse_editable() != 41315) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_parse_editable_incremental() != 11186) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_parse_editable_incremental_style_only() != 17642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_parse_for_save() != 46655) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_render_preview() != 56336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_render_previews() != 25843) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_reset_state() != 18608) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_method_cindermarkparser_toggle_checkbox() != 24460) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cindermark_checksum_constructor_cindermarkparser_new() != 51368) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all